name: test build
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        platform: [ubuntu-latest]
        os:
          - centos7
    runs-on: ${{ matrix.platform }}
    steps:
    - name: install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: checkout code
      uses: actions/checkout@v2
    - name: build
      run: make linux
    - name: go fmt
      run: test -z "$(gofmt -s -l . | tee /dev/stderr)"
